library("MASS")
library(e1071)
library(rpart)
library(rpart.plot)
data(iris)
head(iris)
str(iris)
seed(9580)
g<-runif(nrow(iris))
irisr<-iris[order(g),]
m3<-rpart(Species~.,data=irisr[1:100,],method="class")
m3
rpart.plot(m3)
p3<-predict(m3,irisr[101:150,],type="class")
p3
table(irisr[101:150,5],predicted=p3)
